// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpujlgyujfdypvtvprkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwdWpsZ3l1amZkeXB2dHZwcmtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNzcwODAsImV4cCI6MjA1ODg1MzA4MH0.cWJ2HgQ3r3YUdmrSyJLcW_K5gvbJdN3Xabz0cKh_gok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);